name: test-fetch_token
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - './fetch-github-token/**'
      - '.github/workflows/test-fetch_token.yml'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./fetch-github-token
        with:
          vault-instance: "ci-prod"
